name: core/build

on: [ push,  pull_request ]

jobs:

  test:

    runs-on: ubuntu-20.04
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
    - name: install dotnet.preview
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0-preview.*
    - name: restore
      run: dotnet restore
    - name: build
      run: dotnet build --configuration Debug --no-restore
    - name: test
      run: echo "no test specified yet"
